### ISSUE TITLE
Bad data for stations on 2012-11-05

### ISSUE THREAD

**Issue by 153957** [HiSPARC/datastore#12]
Data can not be processed for the ESD.
HDF5 errors occur when reading its data from the raw datastore.
Perhaps all data for that station needs to be removed..

Errors for stations 10, 303, 504.

**Comment by davidfokkema** [comment]
Data cannot be reprocessed now but were processed some time in the past?

**Comment by 153957** [comment]
Yes, the issue was also reported here: HiSPARC/publicdb#63
Summaries with plots existed for those stations on that date.
(I just removed the summaries for station 10, 303, and 504.)
They do have an events table in the raw data, but processing fails with various errors.
Perhaps that file is partly corrupted.

**Comment by 153957** [comment]
Fixed in ed35e48b14d3a56d9c8144c6a5ee54f6534be992
