### ISSUE TITLE
Restarting httpd (change config) sometimes leaves old threads running

### ISSUE THREAD

**Issue by 153957** [HiSPARC/datastore#16]
I added two new stations in the Publicdb; 521 and 522.
When I converted 501 to 521 it sometimes got a 206 return code, which means unknown station number. This error was also logged on frome, in a thread with a process ID different from the other threads running at the time, meaning it was not properly killed when `hisparc-datastore` tried to reload httpd.

**Comment by davidfokkema** [comment]
This is probably fixed in publicdb#158. We're switching to uWSGI.
