### ISSUE TITLE
Move GPS test data from stations 501 and 502 to a test stations

### ISSUE THREAD

**Issue by 153957** [HiSPARC/datastore#5]
For a GPS offset test station 501 and 502 were triggered simultaneously using a pulsegenerator. The data is poluting the real cosmic data. The data is easily identified by the trace signals (no pulses, external trigger) and the interval between events (250 ms). Moreover, we performed the tests so we know the dates: From 2011/10/21 upto and including 2011/10/31.
We should move this data away from these stations and store under test stations. Stations 94 and 95 are obvious candidates, since those are used for similar tests and started data taking after the 501-502 tests. We should ensure that 94/95 also recieve configs from 501/502 to get the right gps coordinates.

**Comment by 153957** [comment]
Around noon on 2011/10/21 both stations were put in DAQ mode and had their configs sent to the datastore, those should also be moved to the new location (perhaps changing 'detnum' value from 501/502 to 94/95?)

from [501-start](http://data.hisparc.nl/show/stations/502/2011/10/21/) to [501-end](http://data.hisparc.nl/show/stations/501/2011/10/31/)
from [502-start](http://data.hisparc.nl/show/stations/501/2011/10/21/) to [502-start](http://data.hisparc.nl/show/stations/502/2011/10/31/)

**Comment by 153957** [comment]
On a side note, I moved data from station 13401 from cluster_okehampton to cluster_bristol.
It was created in a 'cluster' Okehampton, while it should have been in a 'subcluster' Okehampton.
I moved Okehampton to be a subcluster of Bristol on March 12th. So all data before that was required to move.

This also required moving the already generated esd nodes to the correct location and updating the ESD Coincidences.

**Comment by 153957** [comment]
What shall we do with the real data on 2011/10/21 and 2011/10/31? Also move that, leave it, remove it?
the 'leave it' and 'remove it' will require renormalization of the event ids and trace ids..

**Comment by davidfokkema** [comment]
We started this so we would not pollute our real data. Let's not pollute our test data instead! So either leave it, or remove it. And since we'll have to renormalise ids anyway, let's leave it.

Another option (hardly any work) is to remove both 2011/10/21 and 2011/10/31. Maybe that's even better, since we'll be sure to not make any mistakes.

**Comment by 153957** [comment]
Ah, that is indeed a safe option. We would need to keep (move to test station) the config tables though.

**Comment by 153957** [comment]
### Task list

Raw data:
- Remove event/blob data from station 501/502 on 2011/10/21 and 2011/10/31
- Move config data from station 501/502 from 2011/10/21 to 94/95
- Move data (events/blobs/configs/error) taken from 2011/10/22 upto and including 2011/10/30 from 501/502 to 94/95

Public database:
- Remove summaries from 501/502 for 2011/10/21 - 2011/10/31
- Remove configurations from 501/502 for 2011/10/21 - 2011/10/30
- Remove ESD data for 501/502 for 2011/10/21 - 2011/10/31
- Flag coincidences for 2011/10/21 - 2011/10/31 for update
- Run hisparc-update, should pickup new data/configs for test stations

Did I forget anything?

**Comment by 153957** [comment]
Nearly done.
The hisparc-update is already running, so I'll wait with removing the summaries/configurations and settings the flags untill it is done.

**Comment by 153957** [comment]
Updating failed:

I forgot that the configurations are actually stored in blobs! So for 21 Oct the config blobs need to be added to station 94/95.
Also for 31 Oct the config blob should be restored for stations 501/502.

Yay for backups..!

**Comment by davidfokkema** [comment]
Oops, ;-)

**Comment by 153957** [comment]
Done!

**Comment by davidfokkema** [comment]
👍
